### ISSUE TITLE
Accordion and Action Plan template - Tell the court about your agreement.

### ISSUE THREAD

**Issue by CaroRob** [A2JatAKCourts/docassemble-ChangingOrEnforcingYourChildSupportOrder#24]
**Action Plan template**

- [x] Missing How to fill out CSG Affidavit - Where should we stick this in  in this step, should we add a separate direction, "Read or "See how to fill out CSG Affidavit"?
- [x] link is blue and underlines not black and bold. - discuss

**Accordion**

- [x] bulleted list formatting needs fixing
- [x] content missing: - wasn't missing, got lost in poorly formatted bulleted list.

If you do not have a primary custody child support schedule, use one of these forms:
•	Shared Custody Support Calculation, [DR-306](https://public.courts.alaska.gov/web/forms/docs/dr-306.pdf) [Fill-In PDF] for a shared custody schedule, 
•	Hybrid Custody Child Support Calculation, [DR-308](https://public.courts.alaska.gov/web/forms/docs/dr-308.pdf) for a hybrid custody child support schedule, or
•	Divided Custody Child Support Calculation, [DR-307](https://public.courts.alaska.gov/web/forms/docs/dr-307.pdf) for a divided custody child support schedule.  
If your parenting schedule also changes include:
•	Parenting Plan Agreement & Order, SHC-1128 [Word](https://courts.alaska.gov/shc/family/docs/shc-1128.docx) | [PDF](https://courts.alaska.gov/shc/family/docs/shc-1128n.pdf)

May also be missing how to fill out CSG guidelines affidavit.

**Comment by CaroRob** [comment]
We discussed conventions for links - form names are bold, form numbers are linked for every form that has a number.  Links in this step are bold for display text, body text for URL and nothing in Links in this step is linked.
